#!/usr/bin/env node
// Career OS hub — one self-contained HTML page for every output: pipeline, jobs, market insights (charts), reports, documents, profile.
// Regenerated by tools/daily.sh and by /track. No external requests; light + dark; inline SVG charts (dataviz reference palette).
//
//   node tools/dashboard.mjs                 → reports/dashboard.html (prints the path)
//   node tools/dashboard.mjs --out some.html
import { writeFile, mkdir, readFile, readdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { loadJobs, loadPipeline } from '../lib/store.mjs';
import { STATUSES, dueBuckets, localDate } from './track.mjs';
import { computeInsights } from '../lib/insights.mjs';
import { mdToHtml } from '../lib/md.mjs';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(n); return i >= 0 && args[i + 1] ? args[i + 1] : d; };
const OUT = path.resolve(ROOT, opt('--out', 'reports/dashboard.html'));

// ---------- helpers ----------
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const attr = (s) => esc(s).replace(/\n/g, ' ');
const isoDay = (d = new Date()) => d.toISOString().slice(0, 10);
const fmtDay = (iso) => { if (!iso) return ''; const d = new Date(`${String(iso).slice(0, 10)}T00:00:00`); return isNaN(d) ? String(iso) : d.toLocaleDateString('en-AU', { day: 'numeric', month: 'short' }); };
const ago = (iso) => { const ms = Date.now() - Date.parse(iso); if (isNaN(ms)) return ''; const m = Math.round(ms / 60000); if (m < 60) return `${m} min ago`; const h = Math.round(m / 60); return h < 36 ? `${h} h ago` : `${Math.round(h / 24)} d ago`; };
const link = (url, label, cls = '') => (url ? `<a class="${cls}" href="${attr(url)}" target="_blank" rel="noopener">${esc(label)}</a>` : esc(label));
const fileLink = (p, label) => `<a href="${attr(pathToFileURL(p).href)}" target="_blank" rel="noopener">${esc(label)}</a>`;
const chip = (text, cls = '', title = '') => `<span class="chip ${cls}"${title ? ` title="${attr(title)}"` : ''}>${esc(text)}</span>`;
const RATING_CLASS = { strong: 'good', good: 'accent', stretch: 'warning', skip: 'muted' };
const PRIO_CLASS = { P1: 'p1', P2: 'p2', P3: 'p3' };
const prioChip = (j) => (j?.priority ? chip(j.priority, PRIO_CLASS[j.priority] || '', (j.upsideReasons || []).join(', ')) : '');
const PRIO_ORDER = { P1: 0, P2: 1, P3: 2 }; const RATE_ORDER = { Strong: 0, Good: 1, Stretch: 2, Skip: 3 };
const rank = (j) => (j ? (PRIO_ORDER[j.priority] ?? 3) * 10 + (RATE_ORDER[j.rating] ?? 4) : 99);
const ratingClass = (r) => RATING_CLASS[String(r || '').toLowerCase().split(/\W/)[0]] || 'neutral';
const readOr = async (p, d = '') => { try { return await readFile(p, 'utf8'); } catch { return d; } };

// ---------- load ----------
const db = await loadJobs();
const pipeline = await loadPipeline();
const prefs = JSON.parse(await readOr(path.join(ROOT, 'profile/preferences.json'), '{}'));
const master = (await readOr(path.join(ROOT, 'profile/master-resume.md'))).toLowerCase();
const apps = Array.isArray(pipeline.applications) ? pipeline.applications : [];
const jobs = Object.values(db.jobs || {}).sort((a, b) => (b.prescore ?? -1) - (a.prescore ?? -1) || String(b.firstSeen || '').localeCompare(String(a.firstSeen || '')));
const runs = Array.isArray(db.runs) ? db.runs : [];
const today = localDate();
const weekAgo = isoDay(new Date(Date.now() - 7 * 86400000));
const in14 = isoDay(new Date(Date.now() + 14 * 86400000));
const generatedAt = new Date();
let registered = [];
try { registered = ((await import('../sources/index.mjs')).sources || []).map((s) => s.name); } catch { /* fall back to names in runs */ }
const I = computeInsights(jobs, prefs, master);
const study = JSON.parse(await readOr(path.join(ROOT, 'data/study.json'), 'null')) || [];

// ---------- stats ----------
const rated = (r) => jobs.filter((j) => j.rating === r).length;
const byStatus = Object.fromEntries(STATUSES.map((s) => [s, apps.filter((a) => a.status === s).length]));
const active = apps.filter((a) => a.status !== 'closed').length;
const closingSoon = jobs.filter((j) => j.closesAt && j.closesAt >= today && j.closesAt <= in14 && j.rating !== 'Skip').sort((a, b) => a.closesAt.localeCompare(b.closesAt));
const due = dueBuckets(apps, today);
const lastRun = runs[runs.length - 1];
const stats = [
  ['Jobs seen', jobs.length, `${runs.length} hunt runs · last ${lastRun ? ago(lastRun.at) : '—'}`],
  ['New this week', jobs.filter((j) => j.firstSeen && j.firstSeen >= weekAgo).length, `${jobs.filter((j) => j.firstSeen === isoDay()).length} today`],
  ['Rated Strong / Good', `${rated('Strong')} / ${rated('Good')}`, `${rated('Stretch')} stretch · ${rated('Skip')} skip`],
  ['Active applications', active, STATUSES.filter((s) => byStatus[s]).map((s) => `${s} ${byStatus[s]}`).join(' · ') || 'none yet'],
  ['Follow-ups due', due.overdue.length + due.today.length + due.soon.length, `${due.overdue.length} overdue · ${due.today.length} today · ${due.soon.length} this week`],
  ['Closing within 14 days', closingSoon.length, closingSoon.slice(0, 2).map((j) => `${j.company.slice(0, 18)} ${fmtDay(j.closesAt)}`).join(' · ') || '—'],
];

// ---------- pipeline ----------
const jobOf = (a) => (a.jobId && db.jobs?.[a.jobId]) || null;
function cardHtml(a) {
  const j = jobOf(a); const hist = (a.history || []).slice(-1)[0];
  const folder = a.folder ? path.join(ROOT, a.folder) : null;
  const outputs = folder && existsSync(path.join(folder, 'outputs')) ? path.join(folder, 'outputs') : null;
  return `<article class="card">
    <div class="card-co">${esc(a.company)}</div>
    <div class="card-title">${esc(a.title)}</div>
    ${prioChip(j)}${j?.rating ? chip(j.rating, ratingClass(j.rating)) : ''}${j?.closesAt ? chip(`closes ${fmtDay(j.closesAt)}`, j.closesAt <= in14 ? 'warning' : '') : ''}
    ${a.nextAction ? `<div class="card-next">→ ${esc(a.nextAction)}</div>` : ''}
    <div class="card-meta">${hist ? `${fmtDay(hist.at)} · ${esc(hist.note || hist.status)}` : ''}${a.dueDate ? ` · due ${fmtDay(a.dueDate)}` : ''}</div>
    <div class="card-links">${link(a.url || j?.url, 'posting ↗')}${folder ? ` · ${fileLink(folder, 'folder')}` : ''}${outputs ? ` · ${fileLink(outputs, 'PDFs')}` : ''}</div>
  </article>`;
}
const kanban = STATUSES.map((s) => `<section class="col st-${s}"><header><span class="dot"></span>${esc(s)}<span class="count">${byStatus[s]}</span></header>${apps.filter((a) => a.status === s).sort((a, b) => rank(jobOf(a)) - rank(jobOf(b))).map(cardHtml).join('') || '<div class="empty">—</div>'}</section>`).join('');
const dueRow = (a) => `<li><span class="chip ${a.dueDate && a.dueDate < today ? 'critical' : 'neutral'}">${a.dueDate ? fmtDay(a.dueDate) : 'no date'}</span> <strong>${esc(a.company)}</strong> — ${esc(a.title)} ${chip(a.status, `st-${a.status}`)}${a.nextAction ? `<div class="sub">→ ${esc(a.nextAction)}</div>` : ''}</li>`;
const followups = ['overdue', 'today', 'soon', 'undated'].map((k) => due[k].length ? `<h4>${k === 'soon' ? 'This week' : k === 'undated' ? 'No date, next action set' : k[0].toUpperCase() + k.slice(1)} <span class="count">${due[k].length}</span></h4><ul class="due">${due[k].map(dueRow).join('')}</ul>` : '').join('') || '<p class="muted">Nothing due.</p>';

// ---------- sources health ----------
const perSource = {};
for (const r of runs) for (const s of r.sources || []) { const errs = (r.errors || []).filter((e) => e.startsWith(s + ' ') || e.startsWith(s + ':')).length; perSource[s] = { last: r.at, errors: errs, timedOut: (r.errors || []).some((e) => e.includes(s) && /timed out/.test(e)) }; }
const srcCount = {}; for (const j of jobs) srcCount[j.source] = (srcCount[j.source] || 0) + 1;
const srcNames = [...new Set([...registered, ...Object.keys(perSource), ...Object.keys(srcCount)])];
const NOTES = { adzuna: 'needs free API key (data/secrets.json)', indeed: 'blocked by Cloudflare — browser only', mckinsey: 'Akamai — browser-pane check in /hunt' };
const srcRows = srcNames.map((s) => { const p = perSource[s]; const state = !p ? 'never' : p.timedOut ? 'down' : p.errors ? 'errors' : (Date.now() - Date.parse(p.last)) > 5 * 86400000 ? 'stale' : 'ok'; return `<tr><td><strong>${esc(s)}</strong></td><td>${chip(state, { ok: 'good', errors: 'warning', down: 'critical', stale: 'warning', never: 'muted' }[state])}</td><td>${p ? ago(p.last) : '—'}</td><td class="num">${srcCount[s] || 0}</td><td class="muted">${esc(NOTES[s] || '')}</td></tr>`; }).join('');

// ---------- jobs table ----------
const AUre = new RegExp((prefs.locations?.country_regex || 'perth|sydney|melbourne|brisbane|canberra|adelaide|australia') + '|remote', 'i');
const jobsSorted = [...jobs].sort((a, b) => (a.rating || b.rating ? rank(a) - rank(b) : 0) || (b.prescore ?? 0) - (a.prescore ?? 0));
const jobRows = jobsSorted.map((j) => {
  const desc = (j.description || j.summary || '').slice(0, 1400);
  return `<tr class="job" data-rating="${attr(j.rating || 'unrated')}" data-prio="${attr(j.priority || '')}" data-score="${j.prescore ?? 0}" data-au="${AUre.test(j.location) ? 1 : 0}" data-text="${attr(`${j.title} ${j.company} ${j.location} ${j.source}`.toLowerCase())}">
    <td>${prioChip(j)}</td>
    <td>${j.rating ? chip(j.rating, ratingClass(j.rating)) : '<span class="muted">—</span>'}</td>
    <td><div class="jt">${esc(j.title)}</div><div class="sub">${esc(j.company)}</div></td>
    <td>${esc(j.location.slice(0, 40))}</td>
    <td class="num">${j.prescore ?? ''}</td>
    <td>${fmtDay(j.postedAt)}</td>
    <td>${j.closesAt ? `<span class="${j.closesAt <= in14 ? 'warn-ink' : ''}">${fmtDay(j.closesAt)}</span>` : ''}</td>
    <td>${link(j.url, j.source)}${(j.alsoOn || []).map((a) => ` · ${link(a.url, a.source)}`).join('')}</td>
    <td>${chip(j.status || 'new', j.status && j.status !== 'new' ? `st-${j.status}` : 'muted')}</td>
  </tr><tr class="detail" hidden><td colspan="9">${j.fit ? `<p><strong>Fit:</strong> ${esc(j.fit)}</p>` : ''}<p class="desc">${esc(desc)}${desc.length >= 1400 ? '…' : ''}</p></td></tr>`;
}).join('');

// ---------- charts (inline SVG, single-series horizontal bars) ----------
function barChart(id, title, rows, { color = 'var(--accent)', colorOf = null, unit = '', note = '' } = {}) {
  const max = Math.max(1, ...rows.map((r) => r.value));
  const rowH = 26, labelW = 190, valueW = 56, W = 720, H = rows.length * rowH + 8, barW = W - labelW - valueW - 16;
  const bars = rows.map((r, i) => {
    const w = Math.max(2, Math.round((r.value / max) * barW)); const y = 4 + i * rowH; const c = colorOf ? colorOf(r) : color;
    return `<g class="bar" tabindex="0"><title>${esc(r.label)}: ${r.value}${unit}${r.extra ? ` — ${esc(r.extra)}` : ''}</title>
      <text x="${labelW - 8}" y="${y + 17}" text-anchor="end" class="lbl">${esc(r.label.length > 26 ? r.label.slice(0, 25) + '…' : r.label)}</text>
      <rect x="${labelW}" y="${y + 5}" width="${w}" height="16" rx="4" fill="${c}"></rect>
      <text x="${labelW + w + 8}" y="${y + 17}" class="val">${r.value}${unit}${r.suffix ? ` ${esc(r.suffix)}` : ''}</text></g>`;
  }).join('');
  return `<figure class="chart" id="${id}"><figcaption><strong>${esc(title)}</strong>${note ? `<span class="muted"> · ${esc(note)}</span>` : ''}</figcaption>
    <svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="${attr(title)}">${bars}</svg>
    <details><summary>table</summary><table>${rows.map((r) => `<tr><td>${esc(r.label)}</td><td class="num">${r.value}${unit}</td>${r.extra ? `<td>${esc(r.extra)}</td>` : ''}</tr>`).join('')}</table></details></figure>`;
}
const fam = I.familiesAu.filter(([k]) => k !== 'other').map(([k, v]) => ({ label: k, value: v, extra: `${I.familiesPerth.find(([kk]) => kk === k)?.[1] || 0} in ${I.HOME}` }));
const yrs = ['0–2', '3–4', '5–7', '8+'].map((b) => ({ label: `${b} years`, value: I.yrsAi.find(([k]) => k === b)?.[1] || 0 }));
const unstated = I.n - I.yrsAi.reduce((a, [, v]) => a + v, 0);
const tech = I.techAi.slice(0, 22).map(([k, v]) => { const has = I.HAS[k] ? I.HAS[k].test(master) : null; return { label: k, value: I.pct(v, I.n), extra: has === null ? 'not tracked on resume' : has ? '✅ on resume' : '❌ gap', suffix: has === null ? '' : has ? '✅' : '❌', has }; });
const city = I.aiByCity.map(([k, v]) => ({ label: k, value: v }));
const charts = [
  barChart('c-fam', 'What the market is hiring (postings by title family)', fam, { note: `hover for ${I.HOME} count` }),
  barChart('c-yrs', `Years asked in AU AI roles (n=${I.n} with descriptions; ${unstated} state none)`, yrs, { note: 'the candidate ≈ 2.2 yrs — the 0–4 band plus every unstated ad is addressable' }),
  barChart('c-tech', 'Skills named in AU AI ads vs the candidate\'s resume (% of ads)', tech, { unit: '%', colorOf: (r) => (r.has === false ? 'var(--warning)' : r.has ? 'var(--good)' : 'var(--muted)'), note: '✅ evidenced in master-resume.md · ❌ gap' }),
  barChart('c-city', 'AI / FDE / data-science postings by city', city, { note: 'weighted toward the home city searches' }),
].join('');
const gapsList = I.gaps.slice(0, 8).map(([k, v]) => `<li><strong>${esc(k)}</strong> — ${v} of ${I.n} AU AI ads (${I.pct(v, I.n)}%)</li>`).join('');

// ---------- reports ----------
const reportsDir = path.join(ROOT, 'reports');
const reportFiles = (await readdir(reportsDir)).filter((f) => f.endsWith('.md')).sort((a, b) => b.localeCompare(a));
const pick = (prefix) => reportFiles.find((f) => f.startsWith(prefix));
const reportOrder = [['Shortlist (rated)', pick('shortlist-')], ['Career pathways', pick('career-path-')], ['Market insights', pick('market-insights-')], ['Refresh log', 'refresh-log.md'], ['Latest hunt', pick('hunt-')], ['Weekly review', pick('weekly-')]].filter(([, f]) => f && existsSync(path.join(reportsDir, f)));
const reportPanels = await Promise.all(reportOrder.map(async ([label, f], i) => `<section class="report" id="rep-${i}"${i ? ' hidden' : ''}><div class="rep-head"><h3>${esc(label)}</h3><span class="muted">${esc(f)} · ${fileLink(path.join(reportsDir, f), 'open file')}</span></div><div class="md">${mdToHtml(await readFile(path.join(reportsDir, f), 'utf8'))}</div></section>`));
const reportTabs = reportOrder.map(([label], i) => `<button class="subtab${i ? '' : ' on'}" data-rep="rep-${i}">${esc(label)}</button>`).join('');

// ---------- job packs ----------
const jobsDir = path.join(ROOT, 'jobs');
const folders = existsSync(jobsDir) ? (await readdir(jobsDir)).filter((f) => !f.startsWith('.')) : [];
const packData = await Promise.all(folders.map(async (f) => {
  const dir = path.join(jobsDir, f); const files = (await readdir(dir)).filter((x) => x.endsWith('.md'));
  const outDir = path.join(dir, 'outputs'); const outs = existsSync(outDir) ? (await readdir(outDir)).filter((x) => /\.(pdf|docx)$/i.test(x)) : [];
  const app = apps.find((a) => a.folder === `jobs/${f}`); const j = app ? jobOf(app) : null;
  const jd = await readOr(path.join(dir, 'jd.md')); const title = (jd.match(/^#\s+(.*)/m) || [, f])[1];
  const brief = await readOr(path.join(dir, 'brief.md')); const verdict = (brief.match(/\*\*Verdict:([^*]+)\*\*/) || [, ''])[1].trim();
  const mtime = (await stat(dir)).mtime;
  return { f, dir, files, outDir, outs, app, j, title, brief, verdict, mtime };
}));
packData.sort((a, b) => rank(a.j) - rank(b.j) || b.mtime - a.mtime);
const has = (p, x) => p.files.includes(x);
const docLink = (p, x, label) => (has(p, x) ? fileLink(path.join(p.dir, x), label) : `<span class="muted">${esc(label)} — not yet</span>`);
const pdfs = (p, re, label) => { const xs = p.outs.filter((x) => re.test(x)); return xs.length ? xs.map((x) => fileLink(path.join(p.outDir, x), x.endsWith('.pdf') ? `${label} PDF` : `${label} DOCX`)).join(' · ') : `<span class="muted">${esc(label)} — run /tailor</span>`; };
const docCards = packData.map((p) => `<article class="doc">
    <div class="doc-head"><div><h3>${esc(p.title)}</h3><div class="sub">${esc(p.f)} · updated ${fmtDay(p.mtime.toISOString())}</div></div><div>${prioChip(p.j)} ${p.j?.rating ? chip(p.j.rating, ratingClass(p.j.rating)) : ''} ${p.app ? chip(p.app.status, `st-${p.app.status}`) : ''}</div></div>
    ${p.verdict ? `<p class="verdict">${esc(p.verdict)}</p>` : ''}
    <div class="doc-row"><span class="k">My resume</span>${pdfs(p, /^Resume_/i, 'Resume')}</div>
    <div class="doc-row"><span class="k">Cover letter</span>${pdfs(p, /^CoverLetter_/i, 'Cover letter')}</div>
    <div class="doc-row"><span class="k">Preparation</span>${docLink(p, 'interview-prep.md', 'Interview prep')} · ${docLink(p, 'research.md', 'Company research')} · ${docLink(p, 'network.md', 'Networking plan')}</div>
    <div class="doc-row"><span class="k">Reference</span>${docLink(p, 'jd.md', 'Job description')} · ${docLink(p, 'notes.md', 'Notes')} · ${p.app?.url || p.j?.url ? link(p.app?.url || p.j?.url, 'posting ↗') : ''} · ${fileLink(p.dir, 'folder')}</div>
    ${p.brief ? `<details class="brief"><summary>Advice: does it suit me, how to position, trajectory, the company</summary><div class="md">${mdToHtml(p.brief)}</div></details>` : `<div class="doc-row"><span class="k">Advice</span><span class="muted">no brief yet — /tailor writes one</span></div>`}
  </article>`);
const profileDocs = ['master-resume.md', 'certifications.md', 'story-bank.md', 'career-context.md', 'linkedin-audit.md', 'achievements.md', 'preferences.json'].filter((f) => existsSync(path.join(ROOT, 'profile', f))).map((f) => fileLink(path.join(ROOT, 'profile', f), f)).join(' · ');
const masterOuts = existsSync(path.join(ROOT, 'profile/outputs')) ? (await readdir(path.join(ROOT, 'profile/outputs'))).filter((x) => /\.(pdf|docx)$/i.test(x)).map((x) => fileLink(path.join(ROOT, 'profile/outputs', x), x)).join(' · ') : '';

// ---------- profile tab ----------
const certsMd = await readOr(path.join(ROOT, 'profile/certifications.md'));
const reqMd = await readOr(path.join(ROOT, 'profile/requirements.md'));
const sg = prefs.priority_model?.stay_go_factors || {};
const ctxMd = await readOr(path.join(ROOT, 'profile/career-context.md'));
const openQ = (ctxMd.split(/## Open questions for the candidate/)[1] || '').trim();
const achievements = await readOr(path.join(ROOT, 'profile/achievements.md'));
const achCount = (achievements.match(/^- \d{4}-\d{2}-\d{2}/gm) || []).length;
const studyRows = study.slice(-8).reverse().map((s) => `<tr><td>${fmtDay(s.date)}</td><td>${esc(s.bank || '')}</td><td class="num">${s.correct}/${s.asked}</td><td>${esc((s.weakTopics || []).join(', '))}</td></tr>`).join('');

// ---------- client JS ----------
const clientJS = `
(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  // theme
  const root=document.documentElement; const saved=(()=>{try{return localStorage.getItem('theme')}catch{return null}})(); if(saved) root.dataset.theme=saved;
  $('#theme').onclick=()=>{const cur=root.dataset.theme||'auto'; const next=cur==='auto'?'dark':cur==='dark'?'light':'auto'; if(next==='auto') delete root.dataset.theme; else root.dataset.theme=next; try{next==='auto'?localStorage.removeItem('theme'):localStorage.setItem('theme',next)}catch{} $('#theme').textContent='Theme: '+next;};
  // tabs
  const showTab=(id)=>{$$('.tab').forEach(b=>b.classList.toggle('on',b.dataset.tab===id)); $$('.pane').forEach(p=>p.hidden=p.id!=='pane-'+id); try{localStorage.setItem('tab',id)}catch{} history.replaceState(null,'','#'+id); window.scrollTo(0,0);};
  $$('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
  const initial=(location.hash||'').slice(1)||(()=>{try{return localStorage.getItem('tab')}catch{return null}})()||'overview'; showTab($$('.pane').some(p=>p.id==='pane-'+initial)?initial:'overview');
  // report subtabs
  $$('.subtab').forEach(b=>b.onclick=()=>{$$('.subtab').forEach(x=>x.classList.toggle('on',x===b)); $$('.report').forEach(r=>r.hidden=r.id!==b.dataset.rep);});
  // jobs table
  const rows=$$('tr.job'); const q=$('#q'), min=$('#min'), minOut=$('#min-out'), au=$('#au'); let rating='all', prio='';
  const apply=()=>{const t=q.value.trim().toLowerCase(), m=+min.value; minOut.textContent=m; let n=0; rows.forEach(r=>{const ok=(rating==='all'||r.dataset.rating===rating)&&(!prio||r.dataset.prio===prio)&&(+r.dataset.score>=m)&&(!au.checked||r.dataset.au==='1')&&(!t||r.dataset.text.includes(t)); r.hidden=!ok; if(!ok){r.nextElementSibling.hidden=true; r.classList.remove('open');} else n++;}); $('#count').textContent=n+' shown';};
  q.oninput=apply; min.oninput=apply; au.onchange=apply; $$('.rf').forEach(b=>b.onclick=()=>{rating=b.dataset.r; $$('.rf').forEach(x=>x.classList.toggle('on',x===b)); apply();}); $$('.pf').forEach(b=>b.onclick=()=>{prio=prio===b.dataset.p?'':b.dataset.p; $$('.pf').forEach(x=>x.classList.toggle('on',x.dataset.p===prio)); apply();}); apply();
  rows.forEach(r=>r.onclick=(e)=>{if(e.target.closest('a'))return; const d=r.nextElementSibling; d.hidden=!d.hidden; r.classList.toggle('open',!d.hidden);});
  // sortable headers
  $$('#jobs th[data-k]').forEach(th=>th.onclick=()=>{const k=th.dataset.k, dir=th.dataset.dir==='asc'?'desc':'asc'; th.dataset.dir=dir; const tb=$('#jobs tbody'); const pairs=rows.map(r=>[r,r.nextElementSibling]); pairs.sort((a,b)=>{const va=k==='score'?+a[0].dataset.score:a[0].children[{title:2,loc:3,posted:5,closes:6}[k]].textContent.trim(), vb=k==='score'?+b[0].dataset.score:b[0].children[{title:2,loc:3,posted:5,closes:6}[k]].textContent.trim(); return (va<vb?-1:va>vb?1:0)*(dir==='asc'?1:-1);}); pairs.forEach(p=>{tb.appendChild(p[0]);tb.appendChild(p[1]);});});
})();`;

// ---------- CSS ----------
const CSS = `
:root { color-scheme: light;
  --page:#f9f9f7; --surface:#fcfcfb; --surface-2:#f3f2ee; --ink:#0b0b0b; --ink-2:#52514e; --muted:#898781; --grid:#e1e0d9; --border:rgba(11,11,11,.10);
  --accent:#2a78d6; --accent-ink:#1c5cab; --accent-soft:#cde2fb; --good:#0ca30c; --good-ink:#006300; --good-soft:#dff3df; --warning:#fab219; --warning-ink:#7a5200; --warning-soft:#fff1d0; --critical:#d03b3b; --critical-ink:#a82b2b; --critical-soft:#fbe0e0;
  --st-shortlisted:#86b6ef; --st-applied:#5598e7; --st-screening:#2a78d6; --st-interview:#1c5cab; --st-offer:#0d366b; --st-closed:#c3c2b7; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { color-scheme: dark;
  --page:#121211; --surface:#1a1a19; --surface-2:#232321; --ink:#ffffff; --ink-2:#c3c2b7; --muted:#898781; --grid:#2e2e2b; --border:rgba(255,255,255,.12);
  --accent:#3987e5; --accent-ink:#8fbcf3; --accent-soft:#1c3a5e; --good:#0ca30c; --good-ink:#8be08b; --good-soft:#12321a; --warning:#c98500; --warning-ink:#f5c66a; --warning-soft:#3a2a08; --critical:#e66767; --critical-ink:#f3a3a3; --critical-soft:#3d1717;
  --st-shortlisted:#3a6fa8; --st-applied:#3987e5; --st-screening:#5fa3f0; --st-interview:#8fbcf3; --st-offer:#cde2fb; --st-closed:#5a5a56; } }
:root[data-theme="dark"] { color-scheme: dark;
  --page:#121211; --surface:#1a1a19; --surface-2:#232321; --ink:#ffffff; --ink-2:#c3c2b7; --muted:#898781; --grid:#2e2e2b; --border:rgba(255,255,255,.12);
  --accent:#3987e5; --accent-ink:#8fbcf3; --accent-soft:#1c3a5e; --good:#0ca30c; --good-ink:#8be08b; --good-soft:#12321a; --warning:#c98500; --warning-ink:#f5c66a; --warning-soft:#3a2a08; --critical:#e66767; --critical-ink:#f3a3a3; --critical-soft:#3d1717;
  --st-shortlisted:#3a6fa8; --st-applied:#3987e5; --st-screening:#5fa3f0; --st-interview:#8fbcf3; --st-offer:#cde2fb; --st-closed:#5a5a56; }
* { box-sizing:border-box } html { background:var(--page) }
body { margin:0; background:var(--page); color:var(--ink); font:14px/1.45 -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; }
a { color:var(--accent-ink) } .muted { color:var(--muted) } .sub { color:var(--ink-2); font-size:12px } .warn-ink { color:var(--warning-ink); font-weight:600 }
header.top { display:flex; align-items:center; gap:16px; padding:14px 22px; border-bottom:1px solid var(--grid); background:var(--surface); position:sticky; top:0; z-index:5; flex-wrap:wrap }
header.top h1 { font-size:18px; margin:0 } header.top .gen { color:var(--muted); font-size:12px }
nav.tabs { display:flex; gap:4px; margin-left:auto; flex-wrap:wrap } .tab { border:1px solid var(--grid); background:var(--surface-2); color:var(--ink-2); padding:6px 12px; border-radius:8px; cursor:pointer; font:inherit } .tab.on { background:var(--accent); color:#fff; border-color:var(--accent) }
#theme { border:1px solid var(--grid); background:var(--surface); color:var(--ink); padding:6px 10px; border-radius:8px; cursor:pointer; font:inherit }
main { padding:18px 22px; max-width:1500px; margin:0 auto } .pane[hidden] { display:none }
.tiles { display:grid; grid-template-columns:repeat(auto-fit, minmax(190px,1fr)); gap:12px; margin-bottom:18px }
.tile { background:var(--surface); border:1px solid var(--grid); border-radius:12px; padding:14px 16px } .tile .k { color:var(--ink-2); font-size:12px } .tile .v { font-size:28px; font-weight:700; margin:4px 0 2px } .tile .s { color:var(--muted); font-size:12px }
h2 { font-size:15px; margin:18px 0 8px } h3 { font-size:14px; margin:0 0 6px } h4 { font-size:13px; margin:12px 0 4px }
.panel { background:var(--surface); border:1px solid var(--grid); border-radius:12px; padding:14px 16px }
.grid2 { display:grid; grid-template-columns:1fr 1fr; gap:14px } @media (max-width:900px){ .grid2 { grid-template-columns:1fr } }
.chip { display:inline-block; padding:1px 8px; border-radius:999px; font-size:11px; font-weight:600; border:1px solid var(--grid); background:var(--surface-2); color:var(--ink-2); white-space:nowrap }
.chip.good { background:var(--good-soft); color:var(--good-ink); border-color:transparent } .chip.accent { background:var(--accent-soft); color:var(--accent-ink); border-color:transparent } .chip.warning { background:var(--warning-soft); color:var(--warning-ink); border-color:transparent } .chip.critical { background:var(--critical-soft); color:var(--critical-ink); border-color:transparent } .chip.muted { color:var(--muted) } .chip.p1 { background:var(--accent); color:#fff; border-color:transparent } .chip.p2 { background:var(--accent-soft); color:var(--accent-ink); border-color:transparent } .chip.p3 { color:var(--muted) }
.pf { border:1px solid var(--grid); background:var(--surface-2); color:var(--ink-2); padding:4px 10px; border-radius:999px; cursor:pointer; font:inherit; font-size:12px } .pf.on { background:var(--accent); color:#fff; border-color:var(--accent) }
.doc-head { display:flex; justify-content:space-between; gap:10px; align-items:flex-start } .verdict { margin:8px 0; padding:8px 10px; background:var(--surface-2); border-left:3px solid var(--accent); border-radius:6px; font-size:13px } details.brief { margin-top:10px } details.brief summary { cursor:pointer; color:var(--accent-ink); font-size:13px } details.brief .md { margin-top:8px; font-size:13px }
${STATUSES.map((s) => `.chip.st-${s} { border-color:var(--st-${s}); color:var(--ink) }`).join(' ')}
.kanban { display:grid; grid-template-columns:repeat(6, minmax(180px,1fr)); gap:10px; overflow-x:auto } .col { background:var(--surface); border:1px solid var(--grid); border-radius:12px; padding:8px; border-top:3px solid var(--grid) }
${STATUSES.map((s) => `.col.st-${s} { border-top-color:var(--st-${s}) } .col.st-${s} .dot { background:var(--st-${s}) }`).join(' ')}
.col header { display:flex; align-items:center; gap:6px; font-weight:600; font-size:13px; padding:4px 6px 8px } .dot { width:8px; height:8px; border-radius:50% } .count { margin-left:auto; color:var(--muted); font-weight:500 } .empty { color:var(--muted); text-align:center; padding:18px }
.card { background:var(--surface-2); border:1px solid var(--grid); border-radius:10px; padding:10px; margin-bottom:8px; font-size:12px } .card-co { font-weight:700 } .card-title { margin:2px 0 6px } .card-next { color:var(--ink-2); margin-top:6px } .card-meta { color:var(--muted); margin-top:6px } .card-links { margin-top:6px }
ul.due { list-style:none; padding:0; margin:0 } ul.due li { padding:6px 0; border-bottom:1px solid var(--grid) }
table { width:100%; border-collapse:collapse; font-size:13px } th, td { text-align:left; padding:7px 8px; border-bottom:1px solid var(--grid); vertical-align:top } th { color:var(--ink-2); font-weight:600; font-size:12px; position:sticky; top:0; background:var(--surface); cursor:pointer } td.num, th.num { text-align:right; font-variant-numeric:tabular-nums }
.filters { display:flex; gap:10px; align-items:center; flex-wrap:wrap; margin:8px 0 10px } .filters input[type=search] { padding:6px 10px; border:1px solid var(--grid); border-radius:8px; background:var(--surface); color:var(--ink); min-width:220px; font:inherit }
.rf { border:1px solid var(--grid); background:var(--surface-2); color:var(--ink-2); padding:4px 10px; border-radius:999px; cursor:pointer; font:inherit; font-size:12px } .rf.on { background:var(--accent); color:#fff; border-color:var(--accent) }
.table-scroll { overflow:auto; max-height:72vh; border:1px solid var(--grid); border-radius:10px; background:var(--surface) } tr.job { cursor:pointer } tr.job.open td { background:var(--surface-2) } tr.detail td { background:var(--surface-2); color:var(--ink-2); font-size:12px } .desc { white-space:pre-wrap; max-height:260px; overflow:auto; margin:6px 0 0 } .jt { font-weight:600 }
.chart { background:var(--surface); border:1px solid var(--grid); border-radius:12px; padding:12px 14px; margin:0 } .chart figcaption { margin-bottom:6px; font-size:13px } .chart svg { display:block } .chart .lbl { fill:var(--ink-2); font-size:12px } .chart .val { fill:var(--ink); font-size:12px; font-weight:600 } .bar:hover rect, .bar:focus rect { opacity:.8; stroke:var(--ink); stroke-width:1 } .chart details { margin-top:6px; font-size:12px } .chart summary { color:var(--muted); cursor:pointer }
.subtabs { display:flex; gap:6px; flex-wrap:wrap; margin-bottom:10px } .subtab { border:1px solid var(--grid); background:var(--surface-2); color:var(--ink-2); padding:5px 10px; border-radius:8px; cursor:pointer; font:inherit; font-size:12px } .subtab.on { background:var(--accent-soft); color:var(--accent-ink); border-color:transparent }
.report { background:var(--surface); border:1px solid var(--grid); border-radius:12px; padding:14px 18px } .rep-head { display:flex; justify-content:space-between; gap:12px; align-items:baseline; flex-wrap:wrap; border-bottom:1px solid var(--grid); padding-bottom:8px; margin-bottom:8px }
.md { max-width:980px; line-height:1.55 } .md h1 { font-size:20px } .md h2 { font-size:16px; margin-top:20px } .md h3 { font-size:14px; margin-top:16px } .md blockquote { border-left:3px solid var(--grid); margin:8px 0; padding:2px 12px; color:var(--ink-2) } .md code { background:var(--surface-2); padding:1px 5px; border-radius:4px; font-size:12px } .md .tbl { overflow-x:auto } .md li { margin:3px 0 }
.docs { display:grid; grid-template-columns:repeat(auto-fill, minmax(440px,1fr)); gap:12px } .doc { background:var(--surface); border:1px solid var(--grid); border-radius:12px; padding:12px 14px } .doc-row { margin-top:6px; font-size:12px } .doc-row .k { display:inline-block; min-width:96px; color:var(--muted) }
`;

// ---------- page ----------
const html = `<!doctype html>
<html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Career OS</title><style>${CSS}</style></head>
<body>
<header class="top"><h1>Career OS</h1><span class="gen">Generated ${esc(generatedAt.toLocaleString('en-AU', { dateStyle: 'medium', timeStyle: 'short' }))} · ${jobs.length} jobs · ${apps.length} applications · refresh every 3 days (07:00)</span>
  <nav class="tabs">${[['overview', 'Overview'], ['jobs', 'Jobs'], ['insights', 'Insights'], ['reports', 'Reports'], ['documents', 'Job packs'], ['profile', 'Profile']].map(([t, l]) => `<button class="tab" data-tab="${t}">${l}</button>`).join('')}</nav><button id="theme">Theme: auto</button></header>
<main>
<section class="pane" id="pane-overview">
  <div class="tiles">${stats.map(([k, v, s]) => `<div class="tile"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div><div class="s">${esc(s)}</div></div>`).join('')}</div>
  <h2>Pipeline <span class="muted">· node tools/track.mjs move &lt;id&gt; &lt;status&gt;</span></h2><div class="kanban">${kanban}</div>
  <div class="grid2" style="margin-top:14px">
    <div class="panel"><h3>Follow-ups <span class="muted">as of ${esc(today)}</span></h3>${followups}</div>
    <div class="panel"><h3>Closing within 14 days</h3>${closingSoon.length ? `<ul class="due">${closingSoon.map((j) => `<li>${chip(fmtDay(j.closesAt), 'warning')} <strong>${esc(j.company)}</strong> — ${link(j.url, j.title)} ${j.rating ? chip(j.rating, ratingClass(j.rating)) : ''}</li>`).join('')}</ul>` : '<p class="muted">Nothing with a known closing date in the next fortnight.</p>'}
      <h3 style="margin-top:14px">Sources health</h3><div style="overflow-x:auto"><table><thead><tr><th>Source</th><th>State</th><th>Last run</th><th class="num">Jobs stored</th><th>Note</th></tr></thead><tbody>${srcRows}</tbody></table></div></div>
  </div>
</section>
<section class="pane" id="pane-jobs" hidden>
  <div class="filters"><input id="q" type="search" placeholder="Search title / company / location…"><span>${['all', 'Strong', 'Good', 'Stretch', 'Skip', 'unrated'].map((r) => `<button class="rf${r === 'all' ? ' on' : ''}" data-r="${r}">${r}</button>`).join(' ')}</span><span>${['P1', 'P2', 'P3'].map((p) => `<button class="pf" data-p="${p}">${p}</button>`).join(' ')}</span><label>min score <input id="min" type="range" min="0" max="100" value="40"> <span id="min-out">40</span></label><label><input id="au" type="checkbox" checked> Home country / remote only</label><span id="count" class="muted"></span></div>
  <div class="table-scroll"><table id="jobs"><thead><tr><th>Priority</th><th>Rating</th><th data-k="title">Title / company</th><th data-k="loc">Location</th><th class="num" data-k="score">Score</th><th data-k="posted">Posted</th><th data-k="closes">Closes</th><th>Links</th><th>Status</th></tr></thead><tbody>${jobRows}</tbody></table></div>
  <p class="sub">Click a row for Claude's fit note and the description. <strong>Priority</strong> = worth the effort (brand direction vs the current employer, interest, pay — hover a chip for the reasons). <strong>Rating</strong> = can the candidate get it. Score is the deterministic prescore.</p>
</section>
<section class="pane" id="pane-insights" hidden>
  <p class="sub">From ${jobs.length} postings (${I.au.length} in Australia; ${I.aiAu.length} AI/FDE/solutions/data-science, ${I.aiPerth.length} in Perth). Counts are postings, not vacancies. Full write-up in Reports → Market insights.</p>
  <div class="grid2">${charts}</div>
  <div class="panel" style="margin-top:14px"><h3>Biggest resume gaps vs demand</h3><ol>${gapsList}</ol><p class="sub">Close a gap → update profile/master-resume.md → the ✅/❌ column updates on the next refresh.</p></div>
</section>
<section class="pane" id="pane-reports" hidden><div class="subtabs">${reportTabs}</div>${reportPanels.join('')}</section>
<section class="pane" id="pane-documents" hidden>
  <p class="sub">One pack per target job, ordered by priority then fit. Each has the candidate's tailored resume and cover letter, the preparation material, and the advice brief.</p>
  <div class="docs">${docCards.join('') || '<p class="muted">No job folders yet — /tailor creates them.</p>'}</div>
  <div class="panel" style="margin-top:12px"><h3>Profile</h3><div class="doc-row"><span class="k">Source files</span>${profileDocs}</div>${masterOuts ? `<div class="doc-row"><span class="k">Master preview</span>${masterOuts}</div>` : ''}</div>
</section>
<section class="pane" id="pane-profile" hidden>
  <div class="panel" style="margin-bottom:14px"><div class="md">${mdToHtml(reqMd || '# Requirements coverage\n_profile/requirements.md missing_')}</div></div>
  <div class="grid2">
    <div class="panel"><h3>Stay vs go — factors on record</h3><div class="md"><p><strong>Stay:</strong></p><ul>${(sg.stay || []).map((x) => `<li>${esc(x)}</li>`).join('')}</ul><p><strong>Go:</strong></p><ul>${(sg.go || []).map((x) => `<li>${esc(x)}</li>`).join('')}</ul>${sg.interview_line ? `<p><strong>If asked in interview:</strong> ${esc(sg.interview_line)}</p>` : ''}</div><div class="md" style="margin-top:12px">${mdToHtml(certsMd)}</div></div>
    <div class="panel"><h3>Open questions for the candidate</h3><div class="md">${mdToHtml(openQ || '_none recorded_')}</div><h3 style="margin-top:14px">Achievements log</h3><p class="sub">${achCount} dated entries in profile/achievements.md — add with /log.</p><h3 style="margin-top:14px">Study sessions</h3>${studyRows ? `<table><thead><tr><th>Date</th><th>Bank</th><th class="num">Score</th><th>Weak topics</th></tr></thead><tbody>${studyRows}</tbody></table>` : '<p class="muted">None yet — /study.</p>'}</div>
  </div>
</section>
</main>
<script>${clientJS}</script>
</body></html>`;

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, html);
console.log(OUT);
