#!/usr/bin/env node
// Writes reports/shortlist-<today>.md from the live ratings in data/jobs.json (Strong → Good → Stretch, then Skip collapsed). Run after rating.
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { loadJobs, loadPipeline } from '../lib/store.mjs';
const ROOT = fileURLToPath(new URL('../', import.meta.url));
const db = await loadJobs(); const pipe = await loadPipeline();
const today = new Date().toISOString().slice(0, 10);
const inPipe = new Set(pipe.applications.map((a) => a.jobId).filter(Boolean));
const rated = Object.values(db.jobs).filter((j) => j.rating);
const order = { Strong: 0, Good: 1, Stretch: 2, Skip: 3 };
rated.sort((a, b) => order[a.rating] - order[b.rating] || (b.firstSeen || '').localeCompare(a.firstSeen || '') || b.prescore - a.prescore);
const line = (j) => `- **${j.title}** — ${j.company} · ${j.location.slice(0, 45)} · posted ${j.postedAt || '?'}${j.closesAt ? ` · **closes ${j.closesAt}**` : ''}${j.salary ? ` · ${j.salary}` : ''}${j.workType ? ` · ${j.workType}` : ''}${inPipe.has(j.id) ? ' · _in pipeline_' : ''}${j.openCheck && j.openCheck.status !== 'open' ? ` · ⚠ ${j.openCheck.status}` : ''}  \n  [${j.source}](${j.url})${(j.alsoOn || []).map((a) => ` · [${a.source}](${a.url})`).join('')}  \n  ${j.fit || ''}`;
const sec = (r) => { const xs = rated.filter((j) => j.rating === r); return `\n## ${r} (${xs.length})\n${r === 'Skip' ? xs.map((j) => `- ${j.title} — ${j.company}: ${j.fit || ''}`).join('\n') : xs.map(line).join('\n')}\n`; };
const md = `# Shortlist — ${today} (live ratings)\n\n${rated.length} rated of ${Object.keys(db.jobs).length} postings. Ratings are set by /hunt and the scheduled refresh from full descriptions; years-of-experience lines are treated as preferences (the candidate's rule). Regenerated by \`node tools/shortlist.mjs\`.\n${['Strong', 'Good', 'Stretch', 'Skip'].map(sec).join('')}`;
await writeFile(`${ROOT}reports/shortlist-${today}.md`, md);
console.log(`reports/shortlist-${today}.md: ${rated.length} rated`);
